stages:
  - deploy

deploy:
  stage: deploy
  image: sofia:latest

  only:
    - "staging"

  before_script:
   - eval $(ssh-agent -s)
   - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
   - bash -c 'cat <(echo "$SALT_ROSTER") > /etc/salt/roster'

  script:
   - rm -fr '/builds/sofia/ReferenceApplication/.git' && rm -f '/builds/sofia/ReferenceApplication/.gitlab-ci.yml' && rm -f '/builds/sofia/ReferenceApplication/.gitignore'
   - rsync -avz --rsync-path="sudo /usr/bin/rsync" -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" '/builds/sofia/ReferenceApplication/src/' root@refapp.hbbtv.org:/srv/www/htdocs/staging/
   - salt-ssh -l 'error' -i 'refapp.hbbtv.org' -r 'sudo find "/srv/www/htdocs/staging" -type d -exec chmod 775 {} \; && sudo find "/srv/www/htdocs/staging" -type f -exec chmod 664 {} \;' 